/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.Customer;

import Business.Course.CourseDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FitnessClubEnterprise;
import Business.Enterprise.OnlineSalesEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Sales.OnlineSales;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JPanel;

/**
 *
 * @author luliu
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount account;
    private Network network;
    private CourseDirectory myCourse;
    private EcoSystem ecoSystem;
    private HashMap<OnlineSales, Integer> cart;

    /** Creates new form CustomerAreaJPanel */
    public CustomerAreaJPanel(JPanel container, UserAccount account, CustomerOrganization organization,
            Enterprise enterprise, Network network, EcoSystem ecoSystem) {
        this.container = container;
        this.account = account;
        this.ecoSystem = ecoSystem;
        this.network = network;
        myCourse = new CourseDirectory();
        this.cart = new HashMap();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckHistory = new javax.swing.JButton();
        BtnOrderOnline = new javax.swing.JButton();
        BtnViewOrder = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        btnReserveCourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        btnCheckHistory.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnCheckHistory.setForeground(new java.awt.Color(0, 102, 102));
        btnCheckHistory.setText("Check Class History");
        btnCheckHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckHistoryActionPerformed(evt);
            }
        });

        BtnOrderOnline.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BtnOrderOnline.setForeground(new java.awt.Color(153, 0, 0));
        BtnOrderOnline.setText("Buy from Online");
        BtnOrderOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderOnlineActionPerformed(evt);
            }
        });

        BtnViewOrder.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BtnViewOrder.setForeground(new java.awt.Color(153, 0, 0));
        BtnViewOrder.setText("View Online Orders");
        BtnViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewOrderActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel5.setText("Visit Our Online Store:");

        btnRequest.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(102, 0, 255));
        btnRequest.setText("Request an appointment");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnReserveCourse.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnReserveCourse.setForeground(new java.awt.Color(0, 102, 102));
        btnReserveCourse.setText("Reserve Fitness Class");
        btnReserveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveCourseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Please select the service");

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel3.setText("Select a Trainer with you:");

        jLabel4.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        jLabel4.setText("Prefer Public Class?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequest)
                    .addComponent(btnCheckHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOrderOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnCheckHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOrderOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BtnViewOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckHistoryActionPerformed
        // TODO add your handling code here:
        for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof FitnessClubEnterprise){
        CourseViewJPanel courseHistoryViewJPanel = new CourseViewJPanel(container, account, (FitnessClubEnterprise) ent);
        container.add("courseHistoryViewJPanel", courseHistoryViewJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
            }
        }
    }//GEN-LAST:event_btnCheckHistoryActionPerformed

    private void BtnOrderOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderOnlineActionPerformed
        // TODO add your handling code here:
        for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof OnlineSalesEnterprise){
        OrderItemJPanel orderItemJPanel = new OrderItemJPanel(container, account, cart, (OnlineSalesEnterprise) ent);
        container.add("orderItemJPanel", orderItemJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
            }
        }
    }//GEN-LAST:event_BtnOrderOnlineActionPerformed

    private void BtnViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewOrderActionPerformed
        // TODO add your handling code here:
        
        ViewOnlineOrderJPanel viewOrderJPanel = new ViewOnlineOrderJPanel(container, account);
        container.add("viewOrderJPanel", viewOrderJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
            
        
    }//GEN-LAST:event_BtnViewOrderActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof FitnessClubEnterprise){
        RequestTrainerJPanel makeRequestJPanel = new RequestTrainerJPanel(container, account, (FitnessClubEnterprise) ent);
        container.add("makeRequestJPanel", makeRequestJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
            }
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnReserveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveCourseActionPerformed
        // TODO add your handling code here:
        for(Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
            if(ent instanceof FitnessClubEnterprise){
        ReserveCourseJPanel reverseClassJPanel = new ReserveCourseJPanel(container, account, myCourse, (FitnessClubEnterprise) ent);
        container.add("reverseClassJPanel", reverseClassJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
            }
        }
    }//GEN-LAST:event_btnReserveCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOrderOnline;
    private javax.swing.JButton BtnViewOrder;
    private javax.swing.JButton btnCheckHistory;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnReserveCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
